# Generated by Django 4.1 on 2022-09-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_myuser_blog_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='blog_id',
        ),
        migrations.AddField(
            model_name='myuser',
            name='blog_id',
            field=models.ManyToManyField(to='posts.blog_id'),
        ),
    ]
