# Generated by Django 4.1 on 2022-09-05 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_blog_id_remove_myuser_blog_id_myuser_blog_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='blog_id',
        ),
        migrations.AddField(
            model_name='myuser',
            name='blog_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.blog_id'),
        ),
    ]
