# Generated by Django 4.1 on 2022-09-04 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_delete_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='descrription',
            new_name='description',
        ),
    ]
