# Generated by Django 4.1 on 2022-09-04 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_rename_descrription_post_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
